### PR TITLE
Add ml_pathfind and ml_jwt

### PR DESCRIPTION
**Pull request by StiviiK**
# New modules
* https://github.com/eXo-OpenSource/ml_pathfind
* https://github.com/eXo-OpenSource/ml_jwt

### CODE REVIEW

**Comment by StiviiK** [comment]
Modules are for this state feature complete.

**Comment by qaisjp** [comment]
These look like really fantastic modules, thank you very much for the pull request!

We should probably figure out what we want to do with this (mta-modules) repo. I'm not sure if this repo is actually used for anything.

I can't figure out why _new_ modules would be added (even as submodules) to this repo instead of their own standalone repo, other than for publicity.

If publicity is what you're looking for, that's fine: I think it would be a good idea to showcase some exemplary community modules. But in that case I think adding a README.md with links to your projects would be sufficient enough.

/cc @Jusonex since you've worked on ml_pathfind?

**Comment by jushar** [comment]
I'm not sure either. 
I'd probably prefer an integration for modules in Community 2.0. 

The only advantage of this repository is that the modules here are compiled by us, thus trustworthy. We could achieve the same with some form of _verified_ state within the new community also though.

**Comment by StiviiK** [comment]
A (better) integration in the Community sounds like a reasonable Idea. 
Currently it is pretty hard to find modules or even know which exist.

**Pull request closed without merging**
